# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/kglobalaccel': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/purpose': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'frameworks/prison': 'Frameworks/6.24'
    'plasma/kpipewire': '@same'
    'plasma/layer-shell-qt': '@same'
    'libraries/kquickimageeditor': 'v0.6.0'
    'third-party/wayland': '@latest'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
