# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kdbusadons': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kglobalaccel': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwayland': '@stable'
    'frameworks/purpose': '@stable'
