[Desktop Entry]
GenericName=Screenshot Capture Utility
GenericName[ar]=أداة لأخذ اللقطات
GenericName[az]=Ekran şəkli çəkmə aləti
GenericName[bg]=Инструмент за заснемане на екрана
GenericName[ca]=Utilitat de captura de pantalla
GenericName[ca@valencia]=Utilitat de captura de pantalla
GenericName[cs]=Nástroj na snímání obrazovky
GenericName[da]=Værktøj til skærmbilleder
GenericName[de]=Dienstprogramm für Bildschirmfotos
GenericName[el]=Εργαλείο λήψης στιγμιοτύπων οθόνης
GenericName[en_GB]=Screenshot Capture Utility
GenericName[eo]=Ekrankopiokapta Utila^jo
GenericName[es]=Utilidad de capturas de pantalla
GenericName[et]=Ekraani pildistamise tööriist
GenericName[eu]=Pantaila-argazkiak atzemateko baliagarritasuna
GenericName[fi]=Kuvankaappaustyökalu
GenericName[fr]=Utilitaire de capture d'écran
GenericName[gl]=Utilidade para facer capturas de pantalla
GenericName[he]=כלי לצילום מסך
GenericName[hsb]=Pomhadło za fotografowanje wobrazowki
GenericName[hu]=Képernyőkép-rögzítő eszköz
GenericName[ia]=Utilitate de captura de instantaneo de schermo
GenericName[id]=Utilitas Tangkapan Screenshot
GenericName[ie]=Utensile de captura del ecran
GenericName[is]=Skjámyndatökutól
GenericName[it]=Accessorio per catturare schermate
GenericName[ja]=スクリーンショット撮影ユーティリティ
GenericName[ka]=ეკრანის ანაბეჭდის გადაღების პროგრამა
GenericName[ko]=화면 캡처 유틸리티
GenericName[lt]=Ekrano kopijų darymo programa
GenericName[nl]=Hulpmiddel voor het maken van een schermafdruk
GenericName[nn]=Verktøy for å lagra skjermbilete
GenericName[pa]=ਸਕਰੀਨਸ਼ਾਟ ਲੈਣ ਵਾਲੀ ਸਹੂਲਤ
GenericName[pl]=Narzędzie do zrzutów ekranu
GenericName[pt]=Utilitário de Captura de Imagens
GenericName[pt_BR]=Utilitário de captura de tela
GenericName[ro]=Utilitar de capturare a ecranului
GenericName[ru]=Создание снимков экрана
GenericName[sk]=Nástroj na zachytenie snímky obrazovky
GenericName[sl]=Pripomoček za zajem zaslona
GenericName[sr]=Алатка за хватање снимака екрана
GenericName[sr@ijekavian]=Алатка за хватање снимака екрана
GenericName[sr@ijekavianlatin]=Alatka za hvatanje snimaka ekrana
GenericName[sr@latin]=Alatka za hvatanje snimaka ekrana
GenericName[sv]=Verktyg för att ta skärmbilder
GenericName[ta]=திரைப்பிடிப்பு செயலி
GenericName[tr]=Ekran Görüntüsü Yakalama Aracı
GenericName[uk]=Програма для створення знімків екрана
GenericName[x-test]=xxScreenshot Capture Utilityxx
GenericName[zh_CN]=屏幕截图工具
GenericName[zh_TW]=畫面擷取工具
Name=Spectacle
Name[ar]=لاقط الشاشة
Name[az]=Spectacle
Name[bg]=Spectacle
Name[ca]=Spectacle
Name[ca@valencia]=Spectacle
Name[cs]=Spectacle
Name[da]=Spectacle
Name[de]=Spectacle
Name[el]=Spectacle
Name[en_GB]=Spectacle
Name[eo]=Spectacle
Name[es]=Spectacle
Name[et]=Spectacle
Name[eu]=Spectacle
Name[fi]=Spectacle
Name[fr]=Spectacle
Name[gl]=Spectacle
Name[hu]=Spectacle
Name[ia]=Spectacle
Name[id]=Spectacle
Name[ie]=Spectacle
Name[is]=Spectacle
Name[it]=Spectacle
Name[ka]=Spectacle
Name[ko]=Spectacle
Name[lt]=Spectacle
Name[nl]=Spectacle
Name[nn]=Spectacle
Name[pa]=ਸਪੈਕਟਾਕਲ
Name[pl]=Spectacle
Name[pt]=Spectacle
Name[pt_BR]=Spectacle
Name[ro]=Spectacle
Name[ru]=Spectacle
Name[sk]=Spectacle
Name[sl]=Spectacle
Name[sr]=Спектакл
Name[sr@ijekavian]=Спектакл
Name[sr@ijekavianlatin]=Spectacle
Name[sr@latin]=Spectacle
Name[sv]=Spectacle
Name[ta]=ஸ்பெக்டக்குல்
Name[tr]=Deklanşör
Name[uk]=Spectacle
Name[x-test]=xxSpectaclexx
Name[zh_CN]=Spectacle 截图工具
Name[zh_TW]=Spectacle
Comment=Screenshot capture utility
Comment[ar]=أداة التقاط صور الشاشة
Comment[az]=Ekran şəkli çəkmə aləti
Comment[bg]=Инструмент за заснемане на екрана
Comment[ca]=Utilitat per a prendre captures de pantalla
Comment[ca@valencia]=Utilitat per a prendre captures de pantalla
Comment[cs]=Nástroj na snímání obrazovky
Comment[da]=Værktøj til skærmbilleder
Comment[de]=Dienstprogramm für Bildschirmfotos
Comment[el]=Εργαλείο λήψης στιγμιοτύπων οθόνης
Comment[en_GB]=Screenshot capture utility
Comment[eo]=Ekrankopio kapta utileco
Comment[es]=Utilidad de captura de pantalla
Comment[et]=Ekraanipildi tegemise tööriist
Comment[eu]=Pantaila-argazkiak atzemateko baliagarritasuna
Comment[fi]=Kuvakaappaustyökalu
Comment[fr]=Utilitaire de capture d'écran
Comment[gl]=Utilidade para facer capturas de pantalla
Comment[hsb]=Pomhadło za fotografowanje wobrazowki
Comment[hu]=Képernyőkép-rögzítő esezköz
Comment[ia]=Utilitate de captura de instantaneo
Comment[id]=Utilitas Tangkapan Screenshot
Comment[ie]=Utensile de captura del ecran
Comment[is]=Skjámyndatökutól
Comment[it]=Accessorio per catturare schermate
Comment[ja]=スクリーンショット撮影ユーティリティ
Comment[ka]=ეკრანის ანაბეჭდის გადაღების პროგრამა
Comment[ko]=화면 캡처 유틸리티
Comment[lt]=Ekrano kopijų darymo programa
Comment[nl]=Hulpmiddel voor het maken van een schermafdruk
Comment[nn]=Verktøy for å lagra skjermbilete
Comment[pa]=ਸਕਰੀਨਸ਼ਾਟ ਲੈਣ ਵਾਲੀ ਸਹੂਲਤ
Comment[pl]=Narzędzie do zrzutów ekranu
Comment[pt]=Utilitário de captura de imagens do ecrã
Comment[pt_BR]=Utilitário de captura de tela
Comment[ro]=Utilitar de capturare a ecranului
Comment[ru]=Программа для создания снимков экрана
Comment[sk]=Nástroj na zachytenie snímky obrazovky
Comment[sl]=Orodje za zajem zaslona
Comment[sv]=Verktyg för att ta skärmbilder
Comment[ta]=திரைப்பிடிப்பு செயலி
Comment[tr]=Ekran görüntüsü yakalama aracı
Comment[uk]=Програма для створення знімків екрана
Comment[x-test]=xxScreenshot capture utilityxx
Comment[zh_CN]=屏幕截图工具
Comment[zh_TW]=畫面擷取工具
Categories=Qt;KDE;Utility;
Keywords=snapshot;capture;print;screenshot;snipping;snipping tool;snip;
Keywords[ar]=لقطة;صورة;طباعة;شاشة;لقطة شاشة;قصاصة;
Keywords[az]=ekran şəkli;çəkmək;çap;kəsmək;kəsmə aləti;kəs;
Keywords[bg]=екранна снимка;заснемане;отпечатване;моментна снимка;изрязване;
Keywords[ca]=captura de pantalla;captura;imprimeix;impressió;retallat;eina de retall;retall;
Keywords[ca@valencia]=captura de pantalla;captura;imprimix;impressió;retallat;eina de retall;retall;
Keywords[de]=Schnappschuss;Aufnahme;Drucken;Bildschirmfoto;
Keywords[en_GB]=snapshot;capture;print;screenshot;snipping;snipping tool;snip;
Keywords[eo]=momentfoto;kapti;preso;ekrankopio;tranĉado;tranĉa ilo;tranĉi;
Keywords[es]=captura;capturar;imprimir;captura de pantalla;pantallazo;herramienta de recorte;recorte;recortar;
Keywords[eu]=argazkia;atzematea;inprimatzea;pantaila-argazkia;moztea;mozteko tresna;moztu;
Keywords[fi]=kuvakaappaus;kaappaus;kaappaa;tulosta;ruutukaappaus;leike;
Keywords[fr]=instantané ; capture ; impression ; capture d'écran ; découpage ; découpe ;
Keywords[gl]=captura;capturar;imprimir;captura de pantalla;recorte;recortar;ferramenta de recorte;
Keywords[hu]=pillanatkép;rögzítés;nyomtatás;képernyőkép;levágás;vágóeszköz;vágás;
Keywords[ia]=snapshot;capture;print;screenshot;snipping;snipping tool;snip;
Keywords[id]=jepretan;tangkapan;cetak;screenshot;layar;alat;guntingan;snipping;tool;print;snipping tool;
Keywords[is]=myndataka;skot;prent;skjámynd;úrklippa;utanskurður;
Keywords[it]=schermata;cattura;stampa;screenshot;ritagliare;strumento di ritaglio;ritaglio;
Keywords[ka]=snapshot;capture;print;screenshot;snipping;snipping tool;snip;
Keywords[ko]=snapshot;capture;print;screenshot;snipping;snipping tool;snip;스냅샷;캡처;인쇄;스크린샷;스냅;
Keywords[lt]=momentinė kopija;momentine kopija;fotografuoti;padaryti;daryti;spausdinti;ekrano kopija;ekrano kopiją;karpyti;karpymas;apkarpyti;apkirpti;screenshot;ekranvaizdis;iškirpti;iskirpti;karpymo įrankis;karpymo irankis;
Keywords[nl]=momentopname;vangen;afdrukken;schermafdruk;bezig met knippen;kniphulpmiddel;knip;
Keywords[nn]=skjermbilete;skjermskot;utskrift;print;screenshot;utklipp;utklippsverktøy;
Keywords[pa]=ਸਨੈਪਸ਼ਾਟ;ਕੈਪਚਰ ਕਰੋ;ਪਰਿੰਟ;ਸਕਰੀਨਸ਼ਾਟ;ਸਨੈਪ;ਫੋਟੋ ਖਿੱਚਣੀ;ਸਕ੍ਰੀਨਸ਼ਾਟ;ਤਸਵੀਰ;
Keywords[pl]=zrzut;migawka;przechwycenie;drukowanie;wycinane;narzędzie wycinków;wycinek;
Keywords[pt]=fotografia;captura;imprimir;imagem;fotografia;foto;ferramenta de captura;
Keywords[pt_BR]=snapshot;captura;imprimir;captura de tala;recortar;cortar;ferramenta de corte;
Keywords[ro]=captură;instantaneu;print;decupare;
Keywords[ru]=snapshot;capture;print;screenshot;snipping;snipping tool;snip;снимок;захват;печать;снимок экрана;скриншот;обрезка;инструмент обрезки;обрезать;
Keywords[sk]=snímka;zachytiť;tlač;snímka obrazovky;strihanie;strihať
Keywords[sl]=zajem zaslona;zajem;tisk;slika zaslona;zajemalno orodje;zajemanje;snip;
Keywords[sv]=ta;skriva ut;skärmbild;klippa ut;klippa;klippverktyg;klipp;
Keywords[ta]=snapshot;capture;print;screenshot;snipping;snipping tool;snip;திரைப்பிடிப்பு;படமெடு;அச்சு;அச்சிடு;வெட்டு;திரைப்படம்;படம்;பதிவு;
Keywords[tr]=anlık görüntü;yakala;yazdır;ekran görüntüsü;kırpma;kırpma aracı;kırp;
Keywords[uk]=знімок;захоплення;друк;знімок вікна;вікно;знімок екрана;екран;нарізка;нарізання;snapshot;capture;print;screenshot;snipping;snip;
Keywords[x-test]=xxsnapshotxx;xxcapturexx;xxprintxx;xxscreenshotxx;xxsnippingxx;xxsnipping toolxx;xxsnipxx;
Keywords[zh_CN]=snapshot;capture;print;screenshot;snipping;snip;快照;截图;抓取;屏幕截图;捕获;标注;批注;注释;截屏;
Keywords[zh_TW]=snapshot;capture;print;screenshot;snipping;snip;截圖;擷取;截圖程式;snipping tool;
Exec=${CMAKE_INSTALL_PREFIX}/bin/spectacle
Icon=spectacle
Type=Application
StartupNotify=false
Actions=FullScreenScreenShot;CurrentMonitorScreenShot;ActiveWindowScreenShot;RectangularRegionScreenShot;WindowUnderCursorScreenShot;OpenWithoutScreenshot;
X-DBUS-StartupType=Unique
X-DBUS-ServiceName=org.kde.Spectacle
X-KDE-Shortcuts=Print
X-KDE-DBUS-Restricted-Interfaces=org.kde.kwin.Screenshot,org.kde.KWin.ScreenShot2
X-KDE-Wayland-Interfaces=org_kde_plasma_window_management,zkde_screencast_unstable_v1

[Desktop Action FullScreenScreenShot]
Name=Capture Entire Desktop
Name[ar]=التقط سطح المكتب بالكامل
Name[az]=Bütün İş Masalarını çəkmək
Name[bg]=Заснемане на целия работен плот
Name[ca]=Captura l'escriptori sencer
Name[ca@valencia]=Captura l'escriptori sencer
Name[cs]=Zachytit celou plochu
Name[da]=Indfang hele skrivebordet
Name[de]=Die gesamte Arbeitsfläche aufnehmen
Name[el]=Λήψη όλης της επιφάνειας εργασίας
Name[en_GB]=Capture Entire Desktop
Name[eo]=Kapti Tutan Labortablon
Name[es]=Capturar todo el escritorio
Name[et]=Kogu töölaua pildistamine
Name[eu]=Atzeman mahaigain osoa
Name[fi]=Kaappaa koko työpöytä
Name[fr]=Capturer le bureau entier
Name[gl]=Capturar todo o escritorio
Name[he]=צילום כל שולחן עבודה
Name[hsb]=Cyły dźěłowy powjerch fotografować
Name[hu]=Teljes asztal rögzítése
Name[ia]=Captura le scriptorio integre
Name[id]=Tangkap Seluruh Desktop
Name[ie]=Capturar li tot Pupitre
Name[is]=Taka mynd af öllum skjánum
Name[it]=Cattura l'intero desktop
Name[ja]=デスクトップ全体を撮影する
Name[ka]=მთელი სამუშაო მაგიდის ჩაჭერა
Name[ko]=전체 바탕 화면 찍기
Name[lt]=Fotografuoti visą darbalaukį
Name[nl]=Gehele bureaublad vangen
Name[nn]=Ta bilete av heile skrivebordet
Name[pa]=ਪੂਰੇ ਡੈਸਕਟਾਪ ਦੀ ਫੋਟੋ ਲਵੋ
Name[pl]=Zrzuć cały pulpit
Name[pt]=Capturar Todo o Ecrã
Name[pt_BR]=Capturar toda a área de trabalho
Name[ro]=Capturează întregul birou
Name[ru]=Сделать снимок всех экранов
Name[sk]=Zachytiť celú pracovnú plochu
Name[sl]=Zajemi celotno namizje
Name[sr]=Сними целу површ
Name[sr@ijekavian]=Сними целу површ
Name[sr@ijekavianlatin]=Snimi celu površ
Name[sr@latin]=Snimi celu površ
Name[sv]=Ta en bild av hela skrivbordet
Name[ta]=முழு பணிமேடையின் படமெடு
Name[tr]=Tam Masaüstünü Yakala
Name[uk]=Захопити зображення усієї стільниці
Name[x-test]=xxCapture Entire Desktopxx
Name[zh_CN]=截取整个桌面
Name[zh_TW]=擷取整個桌面
Exec=@QtBinariesDir@/qdbus org.kde.Spectacle / FullScreen -1
X-KDE-Shortcuts=Shift+Print

[Desktop Action CurrentMonitorScreenShot]
Name=Capture Current Monitor
Name[ar]=التقط الشّاشة الحاليّة
Name[az]=Cari Monitoru Çəkmək
Name[bg]=Заснемане на текущия монитор
Name[ca]=Captura el monitor actual
Name[ca@valencia]=Captura el monitor actual
Name[cs]=Zachytit současný monitor
Name[da]=Indfang den aktuelle skærm
Name[de]=Den aktuellen Bildschirm aufnehmen
Name[el]=Λήψη της τρέχουσας οθόνης
Name[en_GB]=Capture Current Monitor
Name[eo]=Kaptnu Aktualan Ekranon
Name[es]=Capturar el monitor actual
Name[et]=Aktiivse monitori pildistamine
Name[eu]=Atzeman uneko monitorea
Name[fi]=Kaappaa nykyinen näyttö
Name[fr]=Capturer le moniteur courant
Name[gl]=Capturar o monitor actual
Name[he]=צילום המסך הנוכחי
Name[hsb]=Aktualnu wobrazowku fotografować
Name[hu]=Aktuális monitor rögzítése
Name[ia]=Captura monitor currente
Name[id]=Tangkap Pemantau Saat Ini
Name[ie]=Capturar li actual monitor
Name[is]=Taka mynd af þessum skjá
Name[it]=Cattura il monitor attuale
Name[ja]=現在のモニターを撮影する
Name[ka]=მიმდინარე ეკრანის ჩაჭერა
Name[ko]=현재 모니터 찍기
Name[lt]=Fotografuoti dabartinį monitorių
Name[nl]=Huidige monitor vangen
Name[nn]=Ta bilete av gjeldande skjerm
Name[pa]=ਮੌਜੂਦਾ ਮਾਨੀਟਰ ਦੀ ਫੋਟੋ ਖਿੱਚੋ
Name[pl]=Zrzuć bieżący monitor
Name[pt]=Capturar o Monitor Actual
Name[pt_BR]=Capturar do monitor atual
Name[ro]=Capturează monitorul actual
Name[ru]=Сделать снимок текущего экрана
Name[sk]=Zachytiť aktuálny monitor
Name[sl]=Zajemi trenutni zaslon
Name[sr]=Сними тренутни монитор
Name[sr@ijekavian]=Сними тренутни монитор
Name[sr@ijekavianlatin]=Snimi trenutni monitor
Name[sr@latin]=Snimi trenutni monitor
Name[sv]=Ta en bild av aktuell bildskärm
Name[ta]=தற்போதைய திரையின் படமெடு
Name[tr]=Geçerli Ekranı Yakala
Name[uk]=Захопити зображення на моніторі
Name[x-test]=xxCapture Current Monitorxx
Name[zh_CN]=截取当前显示器
Name[zh_TW]=擷取目前螢幕
Exec=@QtBinariesDir@/qdbus org.kde.Spectacle / CurrentScreen -1


[Desktop Action ActiveWindowScreenShot]
Name=Capture Active Window
Name[ar]=التقط النّافذة النّشطة
Name[az]=Aktiv Pəncərəni Çəkmək
Name[bg]=Заснемане на активен прозорец
Name[ca]=Captura la finestra activa
Name[ca@valencia]=Captura la finestra activa
Name[cs]=Zachytit aktivní okno
Name[da]=Indfang det aktive vindue
Name[de]=Das aktive Fenster aufnehmen
Name[el]=Λήψη του ενεργού παραθύρου
Name[en_GB]=Capture Active Window
Name[eo]=Kapti Aktivan Fenestron
Name[es]=Capturar la ventana activa
Name[et]=Aktiivse akna pildistamine
Name[eu]=Atzeman leiho aktiboa
Name[fi]=Kaappaa aktiivinen ikkuna
Name[fr]=Capturer la fenêtre active
Name[gl]=Capturar a xanela activa
Name[he]=צילום החלון הפעיל
Name[hsb]=Aktiwne wokno fotografować
Name[hu]=Aktív ablak rögzítése
Name[ia]=Captura fenestra active
Name[id]=Tangkap Jendela Aktif
Name[ie]=Capturar li actual fenestre
Name[is]=Taka mynd af virkum glugga
Name[it]=Cattura la finestra attiva
Name[ja]=アクティブウィンドウを撮影する
Name[ka]=აქტიური ფანჯრის ჩაჭერა
Name[ko]=활성 창 찍기
Name[lt]=Fotografuoti aktyvų langą
Name[nl]=Actieve venster vangen
Name[nn]=Ta bilete av aktivt vindauge
Name[pa]=ਸਰਗਰਮ ਵਿੰਡੋ ਦੀ ਫੋਟੋ ਲਵੋ
Name[pl]=Zrzuć bieżące okno
Name[pt]=Capturar a Janela Activa
Name[pt_BR]=Capturar a janela ativa
Name[ro]=Capturează fereastra activă
Name[ru]=Сделать снимок активного окна
Name[sk]=Zachytiť aktívne okno
Name[sl]=Zajemi dejavno okno
Name[sr]=Сними активни прозор
Name[sr@ijekavian]=Сними активни прозор
Name[sr@ijekavianlatin]=Snimi aktivni prozor
Name[sr@latin]=Snimi aktivni prozor
Name[sv]=Ta en bild av aktivt fönster
Name[ta]=செயலில் உள்ள சாளரத்தின் படமெடு
Name[tr]=Etkin Pencereyi Yakala
Name[uk]=Захопити зображення активного вікна
Name[x-test]=xxCapture Active Windowxx
Name[zh_CN]=截取活动窗口
Name[zh_TW]=擷取作用中的視窗
Exec=@QtBinariesDir@/qdbus org.kde.Spectacle / ActiveWindow -1 -1
X-KDE-Shortcuts=Meta+Print

[Desktop Action RectangularRegionScreenShot]
Name=Capture Rectangular Region
Name[ar]=التقط منطقة مستطيلة
Name[az]=Düzbucaqlı sahəni çəkmək
Name[bg]=Заснемане на правоъгълен регион
Name[ca]=Captura una regió rectangular
Name[ca@valencia]=Captura una regió rectangular
Name[cs]=Zachytit obdélníkový výběr na obrazovce
Name[da]=Indfang firkantet område
Name[de]=Einen rechteckigen Bereich aufnehmen
Name[el]=Λήψη ορθογώνιας περιοχής
Name[en_GB]=Capture Rectangular Region
Name[eo]=Kapti Rektangulan Regionon
Name[es]=Capturar una región rectangular
Name[et]=Ristkülikukujulise ala pildistamine
Name[eu]=Atzeman eskualde laukizuzena
Name[fi]=Kaappaa suorakulmainen alue
Name[fr]=Capturer une région rectangulaire
Name[gl]=Capturar unha rexión rectangular
Name[he]=צילון מלבן
Name[hsb]=Praworóžk fotografować
Name[hu]=Téglalap alakú terület rögzítése
Name[ia]=Captura region rectangular
Name[id]=Tangkap Bidang Persegi
Name[ie]=Capturar un rectangulari region
Name[is]=Taka mynd af ferhyrndu svæði
Name[it]=Cattura una regione rettangolare
Name[ja]=矩形領域を撮影する
Name[ka]=ოთხკუთხედი რეგიონის ჩაჭერა
Name[ko]=화면의 사각형 영역 찍기
Name[lt]=Fotografuoti stačiakampę sritį
Name[nl]=Rechthoekig gebied vangen
Name[nn]=Ta bilete av skjermutsnitt
Name[pa]=ਆਇਤਾਕਾਰ ਖੇਤਰ ਦੀ ਫ਼ੋਟੋ ਖਿੱਚੋ
Name[pl]=Zrzuć obszar prostokątny
Name[pt]=Capturar uma Região Rectangular
Name[pt_BR]=Capturar uma região retangular
Name[ro]=Capturează o regiune dreptunghiulară
Name[ru]=Сделать снимок прямоугольной области экрана
Name[sk]=Zachytiť pravouhlú oblasť
Name[sl]=Zajemi pravokotno območje
Name[sr]=Сними правоугаону зону
Name[sr@ijekavian]=Сними правоугаону зону
Name[sr@ijekavianlatin]=Snimi pravougaonu zonu
Name[sr@latin]=Snimi pravougaonu zonu
Name[sv]=Ta en bild av ett rektangulärt område
Name[ta]=செவ்வக பரப்பளவை படமெடு
Name[tr]=Dikdörtgen Bölge Yakala
Name[uk]=Захопити прямокутну область екрана
Name[x-test]=xxCapture Rectangular Regionxx
Name[zh_CN]=截取矩形区域
Name[zh_TW]=擷取矩形區域
Exec=@QtBinariesDir@/qdbus org.kde.Spectacle / RectangularRegion -1
X-KDE-Shortcuts=Meta+Shift+Print

[Desktop Action WindowUnderCursorScreenShot]
Name=Capture Window Under Cursor
Name[ar]=التقط النافذة التي تحت المؤشر
Name[az]=Kursor altındakı pəncərəni çəkmək
Name[bg]=Заснемане на прозорец под курсора
Name[ca]=Captura la finestra sota el cursor
Name[ca@valencia]=Captura la finestra baix el cursor
Name[cs]=Zachytit okno pod kurzorem
Name[de]=Fenster unter dem Mauszeiger aufnehmen
Name[el]=Λήψη παραθύρου υπό τον δρομέα
Name[en_GB]=Capture Window Under Cursor
Name[eo]=Kapti Fenestron Sub Kursoro
Name[es]=Capturar la ventana bajo el cursor
Name[eu]=Atzeman kurtsorearen azpiko leihoa
Name[fi]=Kaappaa osoittimen alla oleva ikkuna
Name[fr]=Capturer la fenêtre sous le curseur
Name[gl]=Capturar a xanela baixo o cursor
Name[hsb]=Wokno pod myšku fotografować
Name[hu]=Kurzor alatti ablak rögzítése
Name[ia]=Captura Fenestra sub Cursor
Name[id]=Tangkap Layar Jendela Di Bawah Kursor
Name[ie]=Capturar un fenestre sub li apuntator
Name[is]=Taka mynd af glugga undir bendli
Name[it]=Cattura finestra sotto il cursore
Name[ja]=カーソル下のウィンドウを撮影する
Name[ka]=კურსორის ქვეშ მყოფი კურსორის ჩაჭერა
Name[ko]=커서 아래 창 캡처
Name[lt]=Fotografuoti langą po žymekliu
Name[nl]=Venster onder cursor opnemen
Name[nn]=Ta bilete av vindauget under peikaren
Name[pa]=ਕਰਸਰ ਹੇਠਲੀ ਵਿੰਡੋ ਦੀ ਫ਼ੋਟੋ ਖਿੱਚੋ
Name[pl]=Zrzuć okno pod wskaźnikiem
Name[pt]=Capturar a Janela sob o Cursor
Name[pt_BR]=Capturar janela sob o cursor
Name[ro]=Capturează fereastra de sub cursor
Name[ru]=Создать снимок окна под курсором мыши
Name[sk]=Zaznamenať okno pod kurzorom
Name[sl]=Zajemi okno pod kazalko
Name[sv]=Ta en bild av fönster under markör
Name[ta]=சுட்டிக்குறிக்கு கீழுள்ள சாளரத்தை படமெடு
Name[tr]=İmleç Altındaki Pencereyi Yakala
Name[uk]=Захопити зображення вікна під вказівником миші
Name[x-test]=xxCapture Window Under Cursorxx
Name[zh_CN]=捕获光标所在窗口
Name[zh_TW]=擷取游標下的視窗
Exec=@QtBinariesDir@/qdbus org.kde.Spectacle / WindowUnderCursor -1 -1
X-KDE-Shortcuts=Meta+Ctrl+Print

[Desktop Action OpenWithoutScreenshot]
Name=Launch without taking a screenshot
Name[ar]=البدء بدون أخذ صورة
Name[az]=Ekran şəkli çəkmədən başladın
Name[bg]=Стартиране без заснемане на екрана
Name[ca]=Llança sense prendre cap captura de pantalla
Name[ca@valencia]=Inicia sense prendre cap captura de pantalla
Name[cs]=Spustit bez sejmutí obrazovky
Name[de]=Ohne Aufnahme eines Bildschirmfotos starten
Name[en_GB]=Launch without taking a screenshot
Name[eo]=Lanĉi sen preni ekrankopion
Name[es]=Lanzar sin realizar una captura de pantalla
Name[eu]=Abiatu pantaila-argazki bat hartu gabe
Name[fi]=Käynnistä kaappaamatta kuvaa
Name[fr]=Lancer sans réalisation de copie d'écran
Name[gl]=Iniciar sen facer unha captura de pantalla
Name[hsb]=Startować, ale nic fotografować
Name[hu]=Indítás képernyőkép készítése nélkül
Name[ia]=Lancea sin prender instantaneo de schermo
Name[id]=Luncurkan tanpa menangkap sebuah tangkapan layar
Name[is]=Ræsa án þess að taka skjámynd
Name[it]=Esegui senza acquisire una schermata
Name[ja]=スクリーンショットを撮影せずに起動する
Name[ka]=ეკრანის ასლის გადაღების გარეშე გაშვება
Name[ko]=스크린샷을 찍지 않고 실행
Name[lt]=Paleisti nepadarant ekrano kopijos
Name[nl]=Starten zonder een schermafdruk te maken
Name[nn]=Køyr utan å ta eit bilete
Name[pa]=ਸਕਰੀਨਸ਼ਾਟ ਲੈਣ ਤੋਂ ਬਿਨਾਂ ਚਲਾਓ
Name[pl]=Uruchom bez wykonania zrzutu ekranu
Name[pt]=Iniciar sem tirar uma fotografia
Name[pt_BR]=Iniciar sem fazer uma captura de tela
Name[ro]=Lansează fără a face o captură de ecran
Name[ru]=Запустить без создания снимка экрана
Name[sk]=Spustiť bez vytvorenia snímky obrazovky
Name[sl]=Zaženi brez zajemanja zaslonskih slik
Name[sv]=Starta utan att ta en skärmbild
Name[ta]=துவக்கும்போது திரைப்பிடிப்பை எடுக்காதே
Name[tr]=Bir Ekran Görüntüsü Almadan Çalıştır
Name[uk]=Запустити без створення знімка
Name[x-test]=xxLaunch without taking a screenshotxx
Name[zh_CN]=启动时不进行截图
Name[zh_TW]=啟動而不擷取螢幕截圖
Exec=@QtBinariesDir@/qdbus org.kde.Spectacle / OpenWithoutScreenshot
